In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
# %cd /content
!nvidia-smi

Tue Sep  6 15:07:52 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Requirement

In [ ]:
%cd /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020
!pip install -r requirements.txt

In [ ]:
# !git clone https://github.com/NVIDIA/apex
%cd apex
!python setup.py install

/content/drive/.shortcut-targets-by-id/1m0rrLIYvPFV92b1Sh7VRMwu4Gyv4k4Vo/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
/content/drive/.shortcut-targets-by-id/1m0rrLIYvPFV92b1Sh7VRMwu4Gyv4k4Vo/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/apex


torch.__version__  = 1.12.1+cu113


running install
running bdist_egg
running egg_info
writing apex.egg-info/PKG-INFO
writing dependency_links to apex.egg-info/dependency_links.txt
writing top-level names to apex.egg-info/top_level.txt
adding license file 'LICENSE'
writing manifest file 'apex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/apex
copying build/lib/apex/__init__.py -> build/bdist.linux-x86_64/egg/apex
copying build/lib/apex/_autocast_utils.py -> build/bdist.linux-x86_64/egg/apex
creating build/bdist.linux-

In [ ]:
# !cp -r /content/drive/MyDrive/AIC_HCM/DOLG/DOLG-pytorch/dataset/data /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020
# !cp -r /content/drive/MyDrive/AIC_HCM/DOLG/DOLG-pytorch/model /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020
# !cp -r /content/drive/MyDrive/AIC_HCM/DOLG/DOLG-pytorch/config.py /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020

### Train

In [ ]:
!pip install albumentations==1.2.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 116 kB 4.7 MB/s 
  Attempting uninstall: albumentations
    Found existing installation: albumentations 1.0.0
    Uninstalling albumentations-1.0.0:
      Successfully uninstalled albumentations-1.0.0


In [ ]:
data_dir='/content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/data'
model_dir='./weights'
%cd /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020

# %cd /content
### If ImportError: cannot import name 'amp' from 'apex' (unknown location)
### => Reinstall Apex

!python -u -m torch.distributed.launch --nproc_per_node=1 train.py --kernel-type b5ns_DDP_final_256_300w_f2_10ep --train-step 0 --data-dir ${data_dir} --image-size 256 --batch-size 32 --enet-type tf_efficientnet_b5_ns --n-epochs 10 --fold 2  --CUDA_VISIBLE_DEVICES 0

/content/drive/.shortcut-targets-by-id/1m0rrLIYvPFV92b1Sh7VRMwu4Gyv4k4Vo/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020
/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
/usr/local/lib/python3.7/dist-packages/albumentations/augmentations/transforms.py:645: FutureWarning: This class has been deprecated. Please use CoarseDropout
  FutureWarning,
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_tor

In [ ]:
# path ="/content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/data/train/"
# import pandas as pd

# df_test = pd.read_csv(path+"train_list.txt")

# with open(path+"test_list.txt","w") as fi:
#   fi.writelines(f'id, landmark_id\n')
#   for i,g in df_test.groupby("landmark_id"):
#     # print("-"*60)
#     line = g.sample(1).iloc[0].values
#     fi.writelines(f'{line[0]},{line[1]}\n')

### Predict


In [ ]:
!ls -lrth /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/weights/b5ns_DDP_final_256_300w_f2_10ep_fold2.pth

-rw------- 1 root root 338M Sep  6 04:22 /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/weights/b5ns_DDP_final_256_300w_f2_10ep_fold2.pth


In [ ]:
!pip install tqdm --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
%cd /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020
import os
import cv2
import glob
import math
import pickle
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import albumentations
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from tqdm.notebook import tqdm as tqdm

import torch
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn
import torch.nn.functional as F
from origin_models import Effnet_Landmark
import geffnet

/content/drive/.shortcut-targets-by-id/1m0rrLIYvPFV92b1Sh7VRMwu4Gyv4k4Vo/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020


In [ ]:
data_dir = '/content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/data/train/'
model_dir = '/content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/weights/'

df = pd.read_csv(os.path.join(data_dir, 'train_list.txt'))
df['filepath'] = df['id'].apply(lambda x: os.path.join(data_dir, '_'.join(x.split("_")[:-1]), f'{x}.jpg'))
df_sub = pd.read_csv(os.path.join(data_dir, 'test_list.txt'))

df_test = df_sub[['id']].copy()
df_test['filepath'] = df_test['id'].apply(lambda x: os.path.join(data_dir, '_'.join(x.split("_")[:-1]), f'{x}.jpg'))

use_metric = True

In [ ]:
device = torch.device('cuda')
batch_size = 16
num_workers = 2
out_dim = 17 

In [ ]:
transforms_672 = albumentations.Compose([
    albumentations.Resize(672, 672),
    albumentations.Normalize()
])

transforms_768 = albumentations.Compose([
    albumentations.Resize(768, 768),
    albumentations.Normalize()
])
transforms_256 = albumentations.Compose([
    albumentations.Resize(256, 256),
    albumentations.Normalize()
])
transforms_512 = albumentations.Compose([
    albumentations.Resize(512, 512),
    albumentations.Normalize()
])


class LandmarkDataset(Dataset):
    def __init__(self, csv, split, mode, transforms=[transforms_672, transforms_256 , transforms_768,transforms_512]):

        self.csv = csv.reset_index()
        self.split = split
        self.mode = mode
        self.transform672 = transforms[0]
        self.transform256 = transforms[1]
        # sel256 = transforms[2]
        self.transform512 = transforms[3]

    def __len__(self):
        return self.csv.shape[0]

    def __getitem__(self, index):
        row = self.csv.iloc[index]
        image = cv2.imread(row.filepath)
        image = image[:, :, ::-1]
        
        res0 = self.transform672(image=image)
        image0 = res0['image'].astype(np.float32)
        image0 = image0.transpose(2, 0, 1)        

        res1 = self.transform256(image=image)
        image1 = res1['image'].astype(np.float32)
        image1 = image1.transpose(2, 0, 1)    
        
        res3 = self.transform512(image=image)
        image3 = res3['image'].astype(np.float32)        
        image3 = image3.transpose(2, 0, 1)   
               
        
        if self.mode == 'test':
            return torch.tensor(image0), torch.tensor(image1) , torch.tensor(image3)

In [ ]:
if df.shape[0] > 100001: # commit
    df = df[df.index % 10 == 0].iloc[500:1000].reset_index(drop=True)
    df_test = df_test.head(101).copy()

dataset_query = LandmarkDataset(df, 'test', 'test')
query_loader = torch.utils.data.DataLoader(dataset_query, batch_size=batch_size, num_workers=num_workers)

dataset_test = LandmarkDataset(df_test, 'test', 'test')
test_loader = torch.utils.data.DataLoader(dataset_test, batch_size=batch_size, num_workers=num_workers)

print(len(dataset_query), len(dataset_test))

5063 17


In [ ]:
dataset_query[0][0].shape,dataset_query[0][1].shape, dataset_query[0][2].shape

(torch.Size([3, 672, 672]),
 torch.Size([3, 256, 256]),
 torch.Size([3, 512, 512]))

In [ ]:
#MODEL
class ArcMarginProduct_subcenter(nn.Module):
    def __init__(self, in_features, out_features, k=3):
        super().__init__()
        self.weight = nn.Parameter(torch.FloatTensor(out_features*k, in_features))
        self.reset_parameters()
        self.k = k
        self.out_features = out_features
        
    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.weight.size(1))
        self.weight.data.uniform_(-stdv, stdv)
        
    def forward(self, features):
        cosine_all = F.linear(F.normalize(features), F.normalize(self.weight))
        cosine_all = cosine_all.view(-1, self.out_features, self.k)
        cosine, _ = torch.max(cosine_all, dim=2)
        return cosine 
        
sigmoid = torch.nn.Sigmoid()
class Swish(torch.autograd.Function):
    @staticmethod
    def forward(ctx, i):
        result = i * sigmoid(i)
        ctx.save_for_backward(i)
        return result
    @staticmethod
    def backward(ctx, grad_output):
        i = ctx.saved_variables[0]
        sigmoid_i = sigmoid(i)
        return grad_output * (sigmoid_i * (1 + i * (1 - sigmoid_i)))

class Swish_module(nn.Module):
    def forward(self, x):
        return Swish.apply(x)

    
 
    
class enet_arcface_FINAL(nn.Module):

    def __init__(self, enet_type, out_dim):
        super(enet_arcface_FINAL, self).__init__()
        self.enet = geffnet.create_model(enet_type.replace('-', '_'), pretrained=None)
        self.feat = nn.Linear(self.enet.classifier.in_features, 512)
        self.swish = Swish_module()
        self.metric_classify = ArcMarginProduct_subcenter(512, out_dim)
        self.enet.classifier = nn.Identity()
 
    def forward(self, x):
        x = self.enet(x)
        x = self.swish(self.feat(x))
        return F.normalize(x), self.metric_classify(x)

In [ ]:
def load_model(model, model_file):
    state_dict = torch.load(model_file)
    if "model_state_dict" in state_dict.keys():
        state_dict = state_dict["model_state_dict"]
    state_dict = {k[7:] if k.startswith('module.') else k: state_dict[k] for k in state_dict.keys()}
#     del state_dict['metric_classify.weight']
    model.load_state_dict(state_dict, strict=True)
    print(f"loaded {model_file}")
    model.eval()    
    return model

In [ ]:
# model_b5 = Effnet_Landmark("tf_efficientnet_b5_ns", out_dim=17)
model_b5 = enet_arcface_FINAL('tf_efficientnet_b5_ns', out_dim=out_dim).to(device)
model_b5 = load_model(model_b5, '/content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/weights/b5ns_DDP_final_256_300w_f2_10ep_fold2.pth')

loaded /content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/weights/b5ns_DDP_final_256_300w_f2_10ep_fold2.pth


In [ ]:
landmark_id2idx = {landmark_id:idx for idx, landmark_id in enumerate(sorted(df['landmark_id'].unique()))}
idx2landmark_id = {idx:landmark_id for idx, landmark_id in enumerate(sorted(df['landmark_id'].unique()))}
pred_mask = pd.Series(df['landmark_id'].unique()).map(landmark_id2idx).values
pred_mask

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
import cv2
img = cv2.imread("/content/drive/MyDrive/AIC_HCM/DOLG/DOLG_Efficientnet_3rd_2020/data/train/all_souls/all_souls_000000.jpg")[:,:,::-1]
img = img[:, :, ::-1]

res = transforms_256(image=img)
img = res['image'].astype(np.float32)
img = img.transpose(2, 0, 1)        
img = torch.tensor(img)
type(img)

torch.Tensor

In [ ]:
TOP_K = 5
CLS_TOP_K = 5
if True:
  with torch.no_grad():
    feats = []
    for img0, img1,img3 in tqdm(query_loader): # 672, 768, 512
      img1 = img1.cuda()
      feat_b5,_        = model_b5(img1)
      feat = torch.cat([feat_b5], dim=1)    
      feats.append(feat.detach().cpu())
    feats = torch.cat(feats)
    feats = feats.cuda()
    feat = F.normalize(feat)        

    PRODS = []
    PREDS = []
    PRODS_M = []
    PREDS_M = []        
    for img0, img1,img3 in tqdm(test_loader):
      img1 = img1.cuda()
      
      probs_m = torch.zeros([16, 17],device=device)
      feat_b5,logits_m      = model_b5(img1); probs_m += logits_m
      feat = torch.cat([feat_b5],dim=1)
      feat = F.normalize(feat)

      probs_m = probs_m/9
      probs_m[:, pred_mask] += 1.0
      probs_m -= 1.0              

      (values, indices) = torch.topk(probs_m, CLS_TOP_K, dim=1)
      probs_m = values
      preds_m = indices              
      PRODS_M.append(probs_m.detach().cpu())
      PREDS_M.append(preds_m.detach().cpu())            
      
      distance = feat.mm(feats.t())
      (values, indices) = torch.topk(distance, TOP_K, dim=1)
      probs = values
      preds = indices    
      PRODS.append(probs.detach().cpu())
      PREDS.append(preds.detach().cpu())

    PRODS = torch.cat(PRODS).numpy()
    PREDS = torch.cat(PREDS).numpy()
    PRODS_M = torch.cat(PRODS_M).numpy()
    PREDS_M = torch.cat(PREDS_M).numpy()

  0%|          | 0/317 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
# map both to landmark_id
gallery_landmark = df['landmark_id'].values
PREDS = gallery_landmark[PREDS]
PREDS_M = np.vectorize(idx2landmark_id.get)(PREDS_M)

In [ ]:
PREDS.min(), PREDS.max(), PREDS_M.min(), PREDS_M.max()

(0, 0, 4, 16)

In [ ]:
print("-"*60)
print(PREDS[:3,:])
print("-"*60)
print(PREDS_M[:3,:])
print("-"*60)
print(PRODS[:3,:])
print("-"*60)
print(PRODS_M[:3,:])

------------------------------------------------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------------------------------------
[[ 9 12 10  7  4]
 [12  9 10  7  4]
 [12  4  9 14 10]]
------------------------------------------------------------
[[1.         0.99997085 0.9999458  0.99994403 0.99993736]
 [1.0000001  0.99996835 0.99995846 0.9999522  0.99994904]
 [0.9999998  0.99993044 0.99992085 0.99991524 0.9999103 ]]
------------------------------------------------------------
[[0.00214636 0.00154817 0.00104082 0.00065649 0.00042582]
 [0.00245392 0.00136721 0.00072479 0.00063276 0.00034571]
 [0.0033977  0.00167596 0.00135243 0.0009793  0.00053322]]


In [ ]:
PRODS_F = []
PREDS_F = []
for i in tqdm(range(PREDS.shape[0])):
    tmp = {}
    classify_dict = {PREDS_M[i,j] : PRODS_M[i,j] for j in range(CLS_TOP_K)}
    for k in range(TOP_K):
        lid = PREDS[i, k]
        tmp[lid] = tmp.get(lid, 0.) + float(PRODS[i, k]) ** 9 * classify_dict.get(lid,1e-8)**10
    pred, conf = max(tmp.items(), key=lambda x: x[1])
    PREDS_F.append(pred)
    PRODS_F.append(conf)

  0%|          | 0/17 [00:00<?, ?it/s]

In [ ]:
print("-"*60)
print(PREDS_F[:10])
print("-"*60)
print(PRODS_F[:10])

------------------------------------------------------------
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
------------------------------------------------------------
[4.998182925429154e-80, 4.998453712210276e-80, 4.997090751090436e-80, 4.99823170150813e-80, 4.997660656964276e-80, 4.998870395769063e-80, 4.9976783446495504e-80, 4.996476462386111e-80, 4.996231474305894e-80, 4.9961179121312465e-80]


In [ ]:
df_test['pred_id'] = PREDS_F
df_test['pred_conf'] = PRODS_F

df_sub['landmarks'] = df_test.apply(lambda row: f'{row["pred_id"]} {row["pred_conf"]}', axis=1)
df_sub.to_csv('submission.csv', index=False)

In [ ]:
df_sub.head()

# id: image_name
# landmarks: class_label score

id                landmarks
0      all_souls_000005  0 4.998182925429154e-80
1      ashmolean_000345  0 4.998453712210276e-80
2        balliol_000067  0 4.997090751090436e-80
3       bodleian_000319   0 4.99823170150813e-80
4  christ_church_001058  0 4.997660656964276e-80